import type { Employee } from './types';

export const employees: Employee[] = [
  { 'Employee ID': 'E001', 'Employee Name': 'Aina Rahman', 'Department': 'HR', 'Job Title': 'HR Executive', 'Supervisor': 'HR Manager', 'Average KPI (%)': 69.25, 'Productivity Rate (%)': 50, 'Final Performance Level': 'Satisfactory', 'Bonus Eligibility': 'No Bonus', 'Reward Type': 'Skill Development Program', 'Retention Action': 'Close Supervision' },
  { 'Employee ID': 'E002', 'Employee Name': 'Daniel Wong', 'Department': 'Finance', 'Job Title': 'Accounts Executive', 'Supervisor': 'Finance Manager', 'Average KPI (%)': 72.75, 'Productivity Rate (%)': 62.5, 'Final Performance Level': 'Satisfactory', 'Bonus Eligibility': 'No Bonus', 'Reward Type': 'Skill Development Program', 'Retention Action': 'Close Supervision' },
  { 'Employee ID': 'E003', 'Employee Name': 'Siti Nur Aisyah', 'Department': 'IT', 'Job Title': 'System Analyst', 'Supervisor': 'IT Manager', 'Average KPI (%)': 85.25, 'Productivity Rate (%)': 83.33, 'Final Performance Level': 'Excellent', 'Bonus Eligibility': 'High Performance Bonus', 'Reward Type': 'Excellence Award', 'Retention Action': 'High Retention Priority' },
  { 'Employee ID': 'E004', 'Employee Name': 'Muhammad Amir', 'Department': 'Marketing', 'Job Title': 'Marketing Officer', 'Supervisor': 'Marketing Manager', 'Average KPI (%)': 79.5, 'Productivity Rate (%)': 54.17, 'Final Performance Level': 'Good', 'Bonus Eligibility': 'Performance Bonus', 'Reward Type': 'Recognition Certificate', 'Retention Action': 'Retention Encouragement' },
  { 'Employee ID': 'E005', 'Employee Name': 'Nur Huda', 'Department': 'Operations', 'Job Title': 'Operations Executive', 'Supervisor': 'Operations Manager', 'Average KPI (%)': 80.25, 'Productivity Rate (%)': 54.17, 'Final Performance Level': 'Good', 'Bonus Eligibility': 'Performance Bonus', 'Reward Type': 'Recognition Certificate', 'Retention Action': 'Retention Encouragement' },
  { 'Employee ID': 'E006', 'Employee Name': 'Jason Lim', 'Department': 'Sales', 'Job Title': 'Sales Executive', 'Supervisor': 'Sales Manager', 'Average KPI (%)': 73.75, 'Productivity Rate (%)': 45.83, 'Final Performance Level': 'Satisfactory', 'Bonus Eligibility': 'No Bonus', 'Reward Type': 'Skill Development Program', 'Retention Action': 'Close Supervision' },
  { 'Employee ID': 'E007', 'Employee Name': 'Farah Nabilla', 'Department': 'HR', 'Job Title': 'HR Assistant', 'Supervisor': 'HR Manager', 'Average KPI (%)': 72.75, 'Productivity Rate (%)': 50, 'Final Performance Level': 'Satisfactory', 'Bonus Eligibility': 'No Bonus', 'Reward Type': 'Skill Development Program', 'Retention Action': 'Close Supervision' },
  { 'Employee ID': 'E008', 'Employee Name': 'Arif Hakim', 'Department': 'IT', 'Job Title': 'Software Engineer', 'Supervisor': 'IT Manager', 'Average KPI (%)': 74.5, 'Productivity Rate (%)': 58.33, 'Final Performance Level': 'Excellent', 'Bonus Eligibility': 'High Performance Bonus', 'Reward Type': 'Excellence Award', 'Retention Action': 'High Retention Priority' },
  { 'Employee ID': 'E009', 'Employee Name': 'Alicia Tan', 'Department': 'Finance', 'Job Title': 'Financial Analyst', 'Supervisor': 'Finance Manager', 'Average KPI (%)': 81.25, 'Productivity Rate (%)': 50, 'Final Performance Level': 'Good', 'Bonus Eligibility': 'Performance Bonus', 'Reward Type': 'Recognition Certificate', 'Retention Action': 'Retention Encouragement' },
  { 'Employee ID': 'E010', 'Employee Name': 'Haziq Firdaus', 'Department': 'Marketing', 'Job Title': 'Content Strategist', 'Supervisor': 'Marketing Manager', 'Average KPI (%)': 72, 'Productivity Rate (%)': 45.83, 'Final Performance Level': 'Satisfactory', 'Bonus Eligibility': 'No Bonus', 'Reward Type': 'Skill Development Program', 'Retention Action': 'Close Supervision' },
  { 'Employee ID': 'E011', 'Employee Name': 'Nursyafiqah', 'Department': 'Operations', 'Job Title': 'Logistics Coordinator', 'Supervisor': 'Operations Manager', 'Average KPI (%)': 70.5, 'Productivity Rate (%)': 41.67, 'Final Performance Level': 'Satisfactory', 'Bonus Eligibility': 'No Bonus', 'Reward Type': 'Skill Development Program', 'Retention Action': 'Close Supervision' },
  { 'Employee ID': 'E012', 'Employee Name': 'Adam Zainal', 'Department': 'Sales', 'Job Title': 'Sales Executive', 'Supervisor': 'Sales Manager', 'Average KPI (%)': 78.5, 'Productivity Rate (%)': 41.67, 'Final Performance Level': 'Good', 'Bonus Eligibility': 'Performance Bonus', 'Reward Type': 'Recognition Certificate', 'Retention Action': 'Retention Encouragement' },
  { 'Employee ID': 'E013', 'Employee Name': 'Intan Sofia', 'Department': 'HR', 'Job Title': 'Recruitment Officer', 'Supervisor': 'HR Manager', 'Average KPI (%)': 66.5, 'Productivity Rate (%)': 70.83, 'Final Performance Level': 'Satisfactory', 'Bonus Eligibility': 'No Bonus', 'Reward Type': 'Skill Development Program', 'Retention Action': 'Close Supervision' },
  { 'Employee ID': 'E014', 'Employee Name': 'Khairul Anwar', 'Department': 'IT', 'Job Title': 'IT Support Officer', 'Supervisor': 'IT Manager', 'Average KPI (%)': 64.5, 'Productivity Rate (%)': 54.17, 'Final Performance Level': 'Satisfactory', 'Bonus Eligibility': 'No Bonus', 'Reward Type': 'Skill Development Program', 'Retention Action': 'Close Supervision' },
  { 'Employee ID': 'E015', 'Employee Name': 'Mei Ling', 'Department': 'Finance', 'Job Title': 'Payroll Officer', 'Supervisor': 'Finance Manager', 'Average KPI (%)': 80.5, 'Productivity Rate (%)': 70.83, 'Final Performance Level': 'Good', 'Bonus Eligibility': 'Performance Bonus', 'Reward Type': 'Recognition Certificate', 'Retention Action': 'Retention Encouragement' },
  { 'Employee ID': 'E016', 'Employee Name': 'Aiman Rosli', 'Department': 'Marketing', 'Job Title': 'Brand Executive', 'Supervisor': 'Marketing Manager', 'Average KPI (%)': 84.5, 'Productivity Rate (%)': 33.33, 'Final Performance Level': 'Excellent', 'Bonus Eligibility': 'High Performance Bonus', 'Reward Type': 'Excellence Award', 'Retention Action': 'High Retention Priority' },
  { 'Employee ID': 'E017', 'Employee Name': 'Sofia Izzati', 'Department': 'Operations', 'Job Title': 'Quality Control Officer', 'Supervisor': 'Operations Manager', 'Average KPI (%)': 69.25, 'Productivity Rate (%)': 50, 'Final Performance Level': 'Satisfactory', 'Bonus Eligibility': 'No Bonus', 'Reward Type': 'Skill Development Program', 'Retention Action': 'Close Supervision' },
  { 'Employee ID': 'E018', 'Employee Name': 'Bryan Lee', 'Department': 'Sales', 'Job Title': 'Business Development Exe', 'Supervisor': 'Sales Manager', 'Average KPI (%)': 78.75, 'Productivity Rate (%)': 54.17, 'Final Performance Level': 'Good', 'Bonus Eligibility': 'Performance Bonus', 'Reward Type': 'Recognition Certificate', 'Retention Action': 'Retention Encouragement' },
  { 'Employee ID': 'E019', 'Employee Name': 'Amirah Khalid', 'Department': 'HR', 'Job Title': 'Training Coordinator', 'Supervisor': 'HR Manager', 'Average KPI (%)': 71, 'Productivity Rate (%)': 58.33, 'Final Performance Level': 'Satisfactory', 'Bonus Eligibility': 'No Bonus', 'Reward Type': 'Skill Development Program', 'Retention Action': 'Close Supervision' },
  { 'Employee ID': 'E020', 'Employee Name': 'Rizky Pratama', 'Department': 'IT', 'Job Title': 'Data Analyst', 'Supervisor': 'IT Manager', 'Average KPI (%)': 65.25, 'Productivity Rate (%)': 50, 'Final Performance Level': 'Satisfactory', 'Bonus Eligibility': 'No Bonus', 'Reward Type': 'Skill Development Program', 'Retention Action': 'Close Supervision' }
];
